#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/lua /usr/libexec/kidblockd.lua
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	ubus call kidblock apply >/dev/null 2>&1
}

service_triggers() {
	procd_add_reload_trigger "kidblock"
}
